#              _            _             _   
#   __ _ _   _| |_ ___  ___| |_ __ _ _ __| |_ 
#  / _` | | | | __/ _ \/ __| __/ _` | '__| __|
# | (_| | |_| | || (_) \__ \ || (_| | |  | |_ 
#  \__,_|\__,_|\__\___/|___/\__\__,_|_|   \__|
# --------------------------------------------

# Wallpaper
exec-once = hyprpaper  
# exec-once = dockerd

# Bar
exec-once = waybar -c ~/dotfiles/config/waybar/config.jsonc -s ~/dotfiles/config/waybar/style.css

# notifications
exec-once = mako       
exec-once = flatpak run md.obsidian.Obsidian    

# Clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
