# Hyprland variables (user-specific)
# Keep only user variables and environment overrides here.

$terminal = kitty
$fileManager = dolphin # kitty yazi   # nautilus
$menu = fuzzel
# $browser = zen-browser # firefox

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = GTK_THEME, Adwaita-dark
env = CLIPHIST_MAX_ITEMS,100
