#           _           _                            _           
# __      _(_)_ __   __| | _____      __  _ __ _   _| | ___  ___ 
# \ \ /\ / / | '_ \ / _` |/ _ \ \ /\ / / | '__| | | | |/ _ \/ __|
#  \ V  V /| | | | | (_| | (_) \ V  V /  | |  | |_| | |  __/\__ \
#   \_/\_/ |_|_| |_|\__,_|\___/ \_/\_/   |_|   \__,_|_|\___||___/
# ---------------------------------------------------------------

# Suppress maximize events for all windows
windowrule = suppress_event maximize, match:class .*

# Network Manager
windowrule = float on, match:title ^(.*Network Manager.*)$
windowrule = move (monitor_w*0.762) (monitor_h*0.03), match:title ^(.*Network Manager.*)$


# Volume Control (pavucontrol)
windowrule = float on, match:title ^(Volume Control)$
windowrule = pin on, match:title ^(Volume Control)$
windowrule = move (monitor_w*0.575) (monitor_h*0.03), match:title ^(Volume Control)$
windowrule = size 800 400, match:title ^(Volume Control)$


# Hyprshot
windowrule = float on, match:title ^(.*Hyprshot.*)$
windowrule = pin on, match:title ^(.*Hyprshot.*)$

# GTK file chooser — Select a Folder
windowrule = float on, match:title ^(Select a Folder)$
windowrule = float on, match:title ^(Save File)$

# Obsidian → workspace 2 (silent)
windowrule = workspace 2 silent, match:class ^(obsidian)$

# Browser Picture-in-Picture
windowrule = float on, match:title ^(Picture-in-Picture)$
windowrule = pin on, match:title ^(Picture-in-Picture)$
windowrule = move (monitor_w*0.695) (monitor_h*0.04), match:title ^(Picture-in-Picture)$


# Fix dragging / focus issues with XWayland floating windows
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false


# Float
windowrule = float on, match:title ^(Чат-бот)$


windowrule = center on, match:class ^(Code)$
windowrule = center on, match:class ^(soffice)$
windowrule = center on, match:class ^(lasview.exe)$
# windowrule = center on, match:float true

